# Generated by Django 3.1.3 on 2020-11-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certs',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('date_added', models.TextField(blank=True, null=True)),
                ('applied', models.IntegerField(blank=True, null=True)),
                ('date_applied', models.TextField(blank=True, null=True)),
                ('banned', models.IntegerField(blank=True, null=True)),
                ('banned_date', models.TextField(blank=True, null=True)),
                ('required_activation', models.IntegerField(blank=True, null=True)),
                ('currently_used', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certs',
                'managed': False,
            },
        ),
    ]
